fasttextModel=/Users/santiagoaguero/dotfiles/languagetool/fastText/lid.176.bin
fasttextBinary=/Users/santiagoaguero/dotfiles/languagetool/fastText/fasttext
languageModel=/Users/santiagoaguero/dotfiles/languagetool/ngrams
