# flexoki-light — palette imported from basecamp/omarchy (themes/flexoki-light/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #FFFCF0
foreground = #100F0F
cursor-color = #100F0F
selection-background = #CECDC3
selection-foreground = #100F0F

palette = 0=#DAD8CE
palette = 1=#D14D41
palette = 2=#879A39
palette = 3=#D0A215
palette = 4=#205EA6
palette = 5=#CE5D97
palette = 6=#3AA99F
palette = 7=#B7B5AC
palette = 8=#100F0F
palette = 9=#D14D41
palette = 10=#879A39
palette = 11=#D0A215
palette = 12=#4385BE
palette = 13=#CE5D97
palette = 14=#3AA99F
palette = 15=#CECDC3
