# gruvbox — palette imported from basecamp/omarchy (themes/gruvbox/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #282828
foreground = #d4be98
cursor-color = #bdae93
selection-background = #d65d0e
selection-foreground = #ebdbb2

palette = 0=#3c3836
palette = 1=#ea6962
palette = 2=#a9b665
palette = 3=#d8a657
palette = 4=#7daea3
palette = 5=#d3869b
palette = 6=#89b482
palette = 7=#d4be98
palette = 8=#3c3836
palette = 9=#ea6962
palette = 10=#a9b665
palette = 11=#d8a657
palette = 12=#7daea3
palette = 13=#d3869b
palette = 14=#89b482
palette = 15=#d4be98
