# last-horizon — palette imported from basecamp/omarchy (themes/last-horizon/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #0c0b0c
foreground = #FAFCFB
cursor-color = #e2dddc
selection-background = #FAFCFB
selection-foreground = #0c0b0c

palette = 0=#0c0b0c
palette = 1=#c38b7b
palette = 2=#87a9b0
palette = 3=#6B5E73
palette = 4=#b59790
palette = 5=#c4d8e2
palette = 6=#a5a0b6
palette = 7=#cfd3cd
palette = 8=#584e51
palette = 9=#c38b7b
palette = 10=#87a9b0
palette = 11=#6B5E73
palette = 12=#b59790
palette = 13=#c4d8e2
palette = 14=#a5a0b6
palette = 15=#e2dddc
