# lumon — palette imported from basecamp/omarchy (themes/lumon/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #16242d
foreground = #d6e2ee
cursor-color = #f2fcff
selection-background = #4d9ed3
selection-foreground = #1b2d40

palette = 0=#1b2d40
palette = 1=#4d86b0
palette = 2=#5e95bc
palette = 3=#6fa4c9
palette = 4=#6fb8e3
palette = 5=#8bc9eb
palette = 6=#b4e4f6
palette = 7=#d6e2ee
palette = 8=#304860
palette = 9=#73a6cb
palette = 10=#86b7d8
palette = 11=#9dcae5
palette = 12=#f2fcff
palette = 13=#b1d8ee
palette = 14=#d1eef8
palette = 15=#ffffff
