# matte-black — palette imported from basecamp/omarchy (themes/matte-black/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #121212
foreground = #bebebe
cursor-color = #eaeaea
selection-background = #515151
selection-foreground = #bebebe

palette = 0=#333333
palette = 1=#D35F5F
palette = 2=#FFC107
palette = 3=#b91c1c
palette = 4=#e68e0d
palette = 5=#D35F5F
palette = 6=#bebebe
palette = 7=#bebebe
palette = 8=#8a8a8d
palette = 9=#B91C1C
palette = 10=#FFC107
palette = 11=#b90a0a
palette = 12=#f59e0b
palette = 13=#B91C1C
palette = 14=#eaeaea
palette = 15=#ffffff
