# retro-82 — palette imported from basecamp/omarchy (themes/retro-82/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #05182e
foreground = #f6dcac
cursor-color = #f6dcac
selection-background = #faa968
selection-foreground = #00172e

palette = 0=#303442
palette = 1=#f85525
palette = 2=#028391
palette = 3=#e97b3c
palette = 4=#faa968
palette = 5=#3f8f8a
palette = 6=#8cbfb8
palette = 7=#a7c9c6
palette = 8=#134e5a
palette = 9=#f85525
palette = 10=#028391
palette = 11=#e97b3c
palette = 12=#faa968
palette = 13=#3f8f8a
palette = 14=#8cbfb8
palette = 15=#f6dcac
