# solitude — palette imported from basecamp/omarchy (themes/solitude/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #101315
foreground = #cacccc
cursor-color = #cacccc
selection-background = #798186
selection-foreground = #101315

palette = 0=#101315
palette = 1=#565d60
palette = 2=#9fa5a9
palette = 3=#d9dbdc
palette = 4=#798186
palette = 5=#aeaeae
palette = 6=#707070
palette = 7=#cbc2be
palette = 8=#4b4e55
palette = 9=#de6145
palette = 10=#343d41
palette = 11=#c9c2b4
palette = 12=#5d6367
palette = 13=#9a9a9a
palette = 14=#707070
palette = 15=#a5aeb4
