# vantablack — palette imported from basecamp/omarchy (themes/vantablack/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #000000
foreground = #ffffff
cursor-color = #ffffff
selection-background = #ffffff
selection-foreground = #000000

palette = 0=#404040
palette = 1=#a4a4a4
palette = 2=#b6b6b6
palette = 3=#cecece
palette = 4=#8d8d8d
palette = 5=#9b9b9b
palette = 6=#b0b0b0
palette = 7=#ececec
palette = 8=#5c5c5c
palette = 9=#a4a4a4
palette = 10=#b6b6b6
palette = 11=#cecece
palette = 12=#8d8d8d
palette = 13=#9b9b9b
palette = 14=#b0b0b0
palette = 15=#ffffff
