# white — palette imported from basecamp/omarchy (themes/white/colors.toml),
# MIT License, Copyright (c) David Heinemeier Hansson.
# Converted to Ghostty palette format for the local theme-switcher (prefix+t).

background = #ffffff
foreground = #000000
cursor-color = #000000
selection-background = #1a1a1a
selection-foreground = #ffffff

palette = 0=#c0c0c0
palette = 1=#2a2a2a
palette = 2=#3a3a3a
palette = 3=#4a4a4a
palette = 4=#1a1a1a
palette = 5=#2e2e2e
palette = 6=#3e3e3e
palette = 7=#000000
palette = 8=#c0c0c0
palette = 9=#2a2a2a
palette = 10=#3a3a3a
palette = 11=#4a4a4a
palette = 12=#1a1a1a
palette = 13=#2e2e2e
palette = 14=#3e3e3e
palette = 15=#000000
