fasttextModel=/Users/santiagoaguero/dotfiles/config/languagetool/fastText/lid.176.bin
fasttextBinary=/Users/santiagoaguero/dotfiles/config/languagetool/fastText/fasttext
languageModel=/Users/santiagoaguero/dotfiles/config/languagetool/ngrams
